youtuber/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :embedded_videos

  root "embedded_videos#new"

end

youtuber/app/models/embedded_video.rb
class EmbeddedVideo < ActiveRecord::Base
end

youtuber/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

youtuber/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

youtuber/app/controllers/embedded_videos_controller.rb
class EmbeddedVideosController < ApplicationController
  before_action :set_embedded_video, only: [:show, :edit, :update, :destroy]

  # GET /embedded_videos
  # GET /embedded_videos.json
  def index
    @embedded_videos = EmbeddedVideo.all
  end

  # GET /embedded_videos/1
  # GET /embedded_videos/1.json
  def show
  end

  # GET /embedded_videos/new
  def new
    @embedded_video = EmbeddedVideo.new
  end

  # GET /embedded_videos/1/edit
  def edit
  end

  # POST /embedded_videos
  # POST /embedded_videos.json
  def create
    @embedded_video = EmbeddedVideo.new(embedded_video_params)

    respond_to do |format|
      if @embedded_video.save
        format.html { redirect_to @embedded_video, notice: 'Embedded video was successfully created.' }
        format.json { render :show, status: :created, location: @embedded_video }
      else
        format.html { render :new }
        format.json { render json: @embedded_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /embedded_videos/1
  # PATCH/PUT /embedded_videos/1.json
  def update
    respond_to do |format|
      if @embedded_video.update(embedded_video_params)
        format.html { redirect_to @embedded_video, notice: 'Embedded video was successfully updated.' }
        format.json { render :show, status: :ok, location: @embedded_video }
      else
        format.html { render :edit }
        format.json { render json: @embedded_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /embedded_videos/1
  # DELETE /embedded_videos/1.json
  def destroy
    @embedded_video.destroy
    respond_to do |format|
      format.html { redirect_to embedded_videos_url, notice: 'Embedded video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_embedded_video
      @embedded_video = EmbeddedVideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def embedded_video_params
      params.require(:embedded_video).permit(:name, :video_url, :photo_url, :color, :autoplay)
    end
end

youtuber/app/helpers/application_helper.rb
module ApplicationHelper
end

youtuber/app/helpers/embedded_videos_helper.rb
module EmbeddedVideosHelper
end

youtuber/app/views/embedded_videos/_form.html.haml
= form_for(@embedded_video) do |f|
  - if @embedded_video.errors.any?
    #error_explanation
      %h2
        = pluralize(@embedded_video.errors.count, "error")
        prohibited this embedded_video from being saved:
      %ul
        - @embedded_video.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :video_url
    %br/
    = f.text_field :video_url
  .field
    = f.label :photo_url
    %br/
    = f.text_field :photo_url
  .field
    = f.label :color
    %br/
    = f.text_field :color
  .field
    = f.label :autoplay
    %br/
    = f.check_box :autoplay
  .actions
    = f.submit

youtuber/app/views/embedded_videos/edit.html.haml
%h1 Editing Embedded Video
= render 'form'
= link_to 'Show', @embedded_video
|
= link_to 'Back', embedded_videos_path

youtuber/app/views/embedded_videos/index.html.haml
%p#notice= notice
%h1 Listing Embedded Videos
%table
  %thead
    %tr
      %th Name
      %th Video url
      %th Photo url
      %th Color
      %th Autoplay
      %th{:colspan => "3"}
  %tbody
    - @embedded_videos.each do |embedded_video|
      %tr
        %td= embedded_video.name
        %td= embedded_video.video_url
        %td= embedded_video.photo_url
        %td= embedded_video.color
        %td= embedded_video.autoplay
        %td= link_to 'Show', embedded_video
        %td= link_to 'Edit', edit_embedded_video_path(embedded_video)
        %td= link_to 'Destroy', embedded_video, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Embedded video', new_embedded_video_path

youtuber/app/views/embedded_videos/new.html.haml
%h1 New Embedded Video
= render 'form'
= link_to 'Back', embedded_videos_path

youtuber/app/views/embedded_videos/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @embedded_video.name
%p
  %strong Video url:
  = @embedded_video.video_url
%p
  %strong Photo url:
  = @embedded_video.photo_url
%p
  %strong Color:
  = @embedded_video.color
%p
  %strong Autoplay:
  = @embedded_video.autoplay
= link_to 'Edit', edit_embedded_video_path(@embedded_video)
|
= link_to 'Back', embedded_videos_path

youtuber/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Youtuber
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Latest compiled and minified CSS
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :rel => "stylesheet"}/
    / Optional theme
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css", :rel => "stylesheet"}/
    / Latest compiled and minified JavaScript
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}
  %body
    .container.container-md
      = yield